version: '2.3'

services:
  jupyter:
    image: david-waterworth/machine-learning:latest
    restart: always
    runtime: nvidia
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - "~/machine-learning/notebooks:/home/jovyan/work"

  nginx:  
    image: nginx
    restart: always
    links: 
      - jupyter
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80